### ISSUE TITLE
Comments are missing

### ISSUE THREAD

**Issue by JupiterRider** [paulloz/godot-csharp-api#3]
First of all: Nice work and thanks for providing this!

I can't find the Comments in the api docs. Are they missing?

That kind of comments:

```csharp
/// <summary>
///  This class performs an important function.
/// </summary>
public class MyClass {}
```

**Comment by paulloz** [comment]
Do you have an example where the summary is provided in the source and doesn't appear on the website?

**Comment by JupiterRider** [comment]
If you create a Godot Project, inside the .mono Folder there is a file called: GodotSharp.xml

For example this property:
```xml
        <member name="P:Godot.OS.VsyncEnabled">
            <summary>
            <para>If <c>true</c>, vertical synchronization (Vsync) is enabled.</para>
            </summary>
        </member>
```

Cannot find the comment in the docs:
https://paulloz.github.io/godot-csharp-api/3.5/Godot.OS.html#Godot_OS_VsyncEnabled

**Comment by paulloz** [comment]
I'll need to scour the DocFX documentation to see if that's something to configure or not. I would've thought it'd be extracted by default.

**Comment by JupiterRider** [comment]
In your Readme you say `Drop the API files inside src/<version>/`
Where do you get the API Files from?

**Comment by paulloz** [comment]
You have all the files in the `.zip` when you download Godot.

**Comment by paulloz** [comment]
Appears that I simply failed miserably during the last update to 3.5. Should be fixed now.

**Comment by paulloz** [comment]
Thank you very much for the report BTW.
